domain_path: C:\Users\Arf\Desktop\ip_camera\zynq\IP-Camera-on-board-Antminer-S9\ip_camera\ip_camera_platform\camera_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: E:\xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
